### ISSUE TITLE
Generate a lot of tmp files.

### ISSUE THREAD

**Issue by qdwang** [oschwald/SublimeLinter-contrib-rustc#14]
Using SublimeLinter-contrib-rustc generates a lot of tmp files. How can I solve that?

**Comment by arthurprs** [comment]
I'm having the same issue.

**Comment by oschwald** [comment]
What options are you using?

**Comment by arthurprs** [comment]
Sorry, I was mistaken. The actual culprit was the rust-autocomplete plugin.

**Comment by qdwang** [comment]
After removing the RustAutoComplete plugin, the problem is gone.
