### ISSUE TITLE
Cargo multiple bin linting

### ISSUE THREAD

**Issue by Kerosene2000** [oschwald/SublimeLinter-contrib-rustc#19]
Hello,

When you use the default way to build multiple binaries with cargo, this SublimeLinter doesn't handle this correctly and throw me this error:
```
extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
```

I tried to add custom args in the sublimeLinter Config User file but, it seems they are given to rustc and not handled by cargo...

My file tree:
- src/
  - bin/
    - server.rs
    - client.rs

Thanks !

**Comment by oschwald** [comment]
Does this still occur if you use the new cargo check option?

**Comment by Kerosene2000** [comment]
I didn't try... Sorry

**Comment by ekimgit** [comment]
Seems not to work for me, or I don't know how to pass options to cargo or rust via the 'custom args' settings in the sublimeLinter Config User file

**Comment by Kerosene2000** [comment]
`Cargo check` needs to fix this :disappointed: 
https://github.com/rsolomo/cargo-check/issues/4
