### ISSUE TITLE
Linter produces one tmp file in Sublime Text 3 for every change

### ISSUE THREAD

**Issue by adrianbrink** [oschwald/SublimeLinter-contrib-rustc#22]
Hi,

every time I change on character the linter creates one tmp file in Sublime Text 3. I can tell that it might be the later because it doesn't create a tmp file when I type comments. Otherwise every keystroke produces one tmp file.

I'm running on the newest OSX and newest Sublime 3.

Any help would be appreciated.

**Comment by iDev0urer** [comment]
@adrianbrink Do you have the RustAutoComplete package installed as well?

**Comment by dortamiguel** [comment]
@watzon I don't have it installed but Im getting lots of tmp files
