### ISSUE TITLE
Linter always fails to find the first crate listed with "extern"

### ISSUE THREAD

**Issue by dchammond** [oschwald/SublimeLinter-contrib-rustc#23]
As the title says, the linter claims it "cannot find crate XXX" where XXX is the first crate declared with "extern crate XXX" in the rust file.

**Comment by Bluebird45** [comment]
Same here, on Debian 8, ST3 build 3183.

**Comment by dallbee** [comment]
Also seeing this issue. Arch Linux, ST3 3114

**Comment by mandeep** [comment]
Same issue ST3 3114 on Linux Mint.

**Comment by mandeep** [comment]
If you're having this issue, make sure you're using Cargo and that the "use-cargo" setting in the SublimeLinter settings is set to true.

**Comment by FichteFoll** [comment]
Can probably be closed.
