### ISSUE TITLE
Cannot install from Package Control

### ISSUE THREAD

**Issue by jwarner112** [oschwald/SublimeLinter-contrib-rustc#27]
Hello,

I'm not sure the cause of this but with Sublime-Text 3 (Build Stable-3126), I cannot seem to install this via PackageControl. When using the "Install a Package" sublime console interface, the package simply does not show up in the suggestions even when typing `sublimelinter-contrib-rustc` directly. The package _does_ exist on PackageControl.io ([here](https://packagecontrol.io/packages/SublimeLinter-contrib-rustc)). I'm not familiar enough with this whole ecosystem to speculate on why this would be happening aside from a lack of being maintained and subsequently being unlisted, but then it shouldn't show up on the site.

I could still install from source but wanted to investigate this oddity as well.

Thanks,
Jeff W.

**Comment by oschwald** [comment]
That is very strange. As far as I know, it is still listed and PackageControl.io does show new installs. That said, I would recommend trying `sublime-rust` instead now that it provides linting support.
