### ISSUE TITLE
Errors show up in the Sublime console, but not as linter errors

### ISSUE THREAD

**Issue by peterkhayes** [oschwald/SublimeLinter-contrib-rustc#28]
I've recently installed the plugin, and am having difficulty exposing errors as red/yellow dots in Sublime.

For example, if I open a file that contains only the following:  
```
asdf
```

I get the following message in the console:
```
error: expected one of `!` or `::`, found `<eof>`
 --> /var/folders/vm/rxlk9n016jq1r6zw_yzxhv1m0000gn/T/SublimeLinter3-peterhayes/example.rs:1:1
  |
1 | asdf
  | ^^^^
```

But no linter errors appear, and when I run the `Show All Errors` command from the command palette, it says that there are no errors.  `rustc` is in my path, and `SublimeLinter` works for JavaScript files just fine.  Any ideas?

**Comment by oschwald** [comment]
The new error format is not currently supported. I would recommend trying `sublime-rust` instead.

**Comment by mandeep** [comment]
@peterkhayes The newest release of SublimeLinter-contrib-rustc should fix this issue. Let us know if you're still having problems.
