### ISSUE TITLE
Unknown flag: '-Z'

### ISSUE THREAD

**Issue by pornel** [oschwald/SublimeLinter-contrib-rustc#29]
My sublime console is full of this error:

```
SublimeLinter: rust output:
error: Unknown flag: '-Z'

Usage:
    cargo rustc [options] [--] [<opts>...] 
```

rustc --version
rustc 1.15.0-beta.5 (10893a9a3 2017-01-19)

It could be due to:
https://github.com/rust-lang/rust/issues/31847

**Comment by oschwald** [comment]
Thanks. I would recommend using [sublime-rust](https://github.com/rust-lang/sublime-rust) instead of this linter, but I am happy to accept PRs to fix outstanding issues.

**Comment by mandeep** [comment]
@pornel This issue should be fixed in the newest release of SublimeLinter-contib-rustc as rustc is no longer running with the -Z flag.
