### ISSUE TITLE
ERROR: rust disabled. 'selector' is mandatory in 'cls.defaults'

### ISSUE THREAD

**Issue by cmajames** [oschwald/SublimeLinter-contrib-rustc#36]
The follow message is emitted to the console when installing SublimeLinter-contrib-rustc using PackageControl:
```
SublimeLinter: linter.py:457          ERROR: rust: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
SublimeLinter: linter.py:582          ERROR: rust disabled. 'selector' is mandatory in 'cls.defaults'.
 See http://www.sublimelinter.com/en/stable/linter_settings.html#selector
```
Even if I add `'rust': { 'selector': 'source.rust' }` to User SublimeLinter.sublime-settings, SublimeLinter emits
```
SublimeLinter: sublime_linter.py:340  No installed linter matches the view.
```

Sublime: v. 3.2.2
PackageControl: v. 3.3.0
SublimeLinter: v. 4.14.0
SublimeLinter-contrib-rustc: v. 1.5.2

**Comment by oschwald** [comment]
I don't use this linter anymore. I'd suggest using https://github.com/rust-lang/rust-enhanced. That said, I am happy to merge fixes for issues. Does https://github.com/oschwald/SublimeLinter-contrib-rustc/pull/35 work for you? It looks like I was waiting for some people to test that before merging.

**Comment by cmajames** [comment]
I'll go ahead and switch over then; thanks.
