### ISSUE TITLE
new version of this package.

### ISSUE THREAD

**Issue by LollipopFt** [oschwald/SublimeLinter-contrib-rustc#37]
hi, i have rewritten this package but without the cargo check function. i would appreciate it if you would point out any errors since you have experience with this, thank you! my repository is [here](https://github.com/LollipopFt/SublimeLinter-contrib-rustc.git). i understand that FichteFoll has made a rewrite for this, but i have no idea how to test plugins out on a previous version of sublime text.

**Comment by oschwald** [comment]
I no longer use Sublime so I am not in a good position to point out errors. However, I'll leave this open for anyone looking for alternatives.
